name: Rails Test and Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
        
  #   - name: Build and push
  #     uses: docker/build-push-action@v5
  #     with:
  #       push: true
  #       tags: imajeetyadav/my-rails-app:latest

  # brakeman:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
    
  #   - name: Run Application
  #     run: docker run -d -p 3000:3000 imajeetyadav/my-rails-app:latest
      
  #   - name: Brakeman Scan
  #     run: |
  #       gem install brakeman
  #       brakeman -o brakeman-output.json

    # - name: Create Issue if Vulnerabilities Found
    #   if: always()
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: POST /repos/${{ github.repository }}/issues
    #     title: Brakeman Vulnerabilities Found
    #     body: |
    #       Brakeman vulnerabilities were found. Please review the `brakeman-output.json` file for details.
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  owasp-zap:
    # needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Run Application
      run: docker run -d -p 3000:3000 imajeetyadav/my-rails-app:latest

    - name: Test
      run: |
        docker ps -al
        sleep 120s
        curl http://localhost:3000
      
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'http://localhost:3000'

    # - name: Create Issue if Vulnerabilities Found
    #   if: always()
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: POST /repos/${{ github.repository }}/issues
    #     title: OWASP ZAP Vulnerabilities Found
    #     body: |
    #       OWASP ZAP vulnerabilities were found. Please review the scan results for details.
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
